name: gdgfoz
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dialog_information_to_specific_platform: 0.0.5
  file: ^5.2.1
  flutter:
    sdk: flutter
  flutter_mobx: ^1.1.0+1
  get_it: ^4.0.2
  http: ^0.12.1
  http_interceptor: ^0.3.0
  image_picker: ^0.6.7+3
  json_annotation: ^3.0.1
  transparent_image: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  mobx_codegen: ^1.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
